'''Lab3: Create a pie chart to illustrate the distribution of a company's revenue
across its various business segments. You have collected data on the revenue
generated by each segment, such as Product A, Product B, Services, and
Licensing. Share your conclusion/analysis.
Input:
segments = ['Product A', 'Product B', 'Services', 'Licensing']
revenue_percentages = [45, 25, 15, 15]'''

import matplotlib.pyplot as plt
# Data for business segments and their revenue percentages
segments = ['Product A', 'Product B', 'Services', 'Licensing']
revenue_percentages = [45, 25, 15, 15]

# Create a pie chart
plt.figure(figsize=(8, 6))
explode = (0.1, 0, 0, 0)  # explode the Product A slice
plt.pie(revenue_percentages, labels=segments, autopct='%1.1f%%', startangle=140, explode=explode)
plt.title('Company Revenue Distribution by Segment')

# Show the plot
plt.axis('equal')  # Equal aspect ratio ensures that pie chart is circular.
plt.show()

# Conclusion/Analysis
# The pie chart illustrates the distribution of the company's revenue across its various business segments. 
# Product A constitutes the largest portion of the revenue, followed by Product B, while Services and Licensing 
# contribute a smaller percentage. This indicates a strong reliance on Product A for revenue generation.
