'''1. Calculate the total revenue generated by two product categories in a store

 Input:

 category1_revenue = np.array([500, 600, 700, 550])

 category2_revenue = np.array([450, 700, 800, 600])'''

import numpy as np
# Define revenue arrays for two product categories
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800, 600])

# Add the arrays to get total revenue
total_revenue = category1_revenue + category2_revenue

# Print result
print("Total revenue:", total_revenue)

